version: "3"

services:
  node-toolkit:
    image: foxonconsulting/node-toolkit:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/user/next-app
    container_name: next-app_cn
    restart: unless-stopped
    stdin_open: true
