version: "3"

services:
  node-toolkit:
    image: node-toolkit
    ports:
      - "2222:22"
      - "3000:3000"
    volumes:
      - ./:/home/user/next-app
    container_name: next-app_cn
    restart: unless-stopped
